name: Build GalacticForwarder

on:
  push:
    branches:
      - main
      - galacticforwarder
      - plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: gradle build

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: GalacticForwarder
          path: build/libs/*.jar
tasks.withType(Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
